orienteering_accounts/event/urls.py
from django.urls import path

from orienteering_accounts.event.views import EventList, EventDetail, EventBills, EventBillsSuccess, EventEntries, EventEntriesPreview

app_name = 'events'

urlpatterns = [
    path('', EventList.as_view(), name='list'),
    path('<int:pk>/', EventDetail.as_view(), name='detail'),
    path('<int:pk>/entries', EventEntries.as_view(), name='entries'),
    path('<int:pk>/entries/<uuid:key>/', EventEntriesPreview.as_view(), name='entries_preview'),
    path('<int:pk>/bills/<uuid:key>/', EventBills.as_view(), name='bills'),
    path('<int:pk>/bills/<uuid:key>/success/', EventBillsSuccess.as_view(), name='bills_success'),
]

orienteering_accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from orienteering_accounts.account.views import AccountLoginView
from orienteering_accounts.core.views import SettingsEdit


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('', include('orienteering_accounts.account.urls')),  # TODO temporary
    path('settings/', SettingsEdit.as_view(), name='settings_detail'),
    path('accounts/', include('orienteering_accounts.account.urls')),
    path('events/', include('orienteering_accounts.event.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orienteering_accounts/event/forms.py
from decimal import Decimal

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit
from django import forms
from datetime import date

from django.core.exceptions import ValidationError
from django.forms import modelformset_factory

from orienteering_accounts.account.models import Account, Transaction
from orienteering_accounts.entry.models import Entry
from orienteering_accounts.event.models import Event


class EventForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['leader'].queryset = Account.objects.order_by('-leader_priority', 'last_name', 'first_name')
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'handled',
            'leader',
            ButtonHolder(
                Submit('save', 'Uložit', css_class='btn btn-success'),
                css_class="modal-footer"
            )
        )

    def read_only(self):
        return self.instance.date <= date.today()

    def is_valid(self):
        if not super().is_valid():
            return False
        return self.instance.handled or self.instance.leader is None

    def save(self, commit=True):
        if 'handled' in self.changed_data and not self.cleaned_data['handled']:
            self.instance.handled_disabled = True
        return super().save(commit=commit)

    class Meta:
        model = Event
        fields = ['handled', 'leader']


class EntryBillForm(forms.ModelForm):

    class Meta:
        models = Entry
        fields = ('debt', 'other_debt', 'debt_note')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.is_bound:
            if self.instance.debt:
                self.initial['debt'] = self.instance.debt
            else:
                self.initial['debt'] = self.instance.debt_init

            if not self.instance.other_debt:
                self.initial['other_debt'] = Decimal(0)

    def clean_debt_note(self):
        other_debt = self.cleaned_data['other_debt']
        debt_note = self.cleaned_data['debt_note']
        if other_debt and not debt_note:
            raise ValidationError("Je nutné vyplnit poznámku, pokud jsou vyplněny další náklady.")

        return debt_note

    def save(self, *args, **kwargs):
        entry = super().save(*args, **kwargs)
        entry.transactions.update_or_create(
            purpose=Transaction.TransactionPurpose.ENTRY,
            account=entry.account,
            defaults=dict(
                amount=-entry.debt
            )
        )
        if entry.other_debt and entry.other_debt > Decimal(0):
            entry.transactions.update_or_create(
                purpose=Transaction.TransactionPurpose.ENTRY_OTHER,
                account=entry.account,
                defaults=dict(
                    amount=-entry.other_debt,
                    note=entry.debt_note
                )
            )
        else:
            # Case when other debt is deleted
            entry.transactions.filter(
                purpose=Transaction.TransactionPurpose.ENTRY_OTHER,
                account=entry.account
            ).delete()

        return entry


EventEntryBillFormSet = modelformset_factory(Entry, fields=['debt', 'other_debt', 'debt_note'], form=EntryBillForm, extra=0)

orienteering_accounts/event/views.py
import uuid
from datetime import timedelta

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.views import View
from django.views.generic import ListView, DetailView
from django_filters.views import FilterView
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404

from orienteering_accounts.account.models import Account
from orienteering_accounts.event.filters import EventFilter
from orienteering_accounts.event.forms import EventForm, EventEntryBillFormSet
from orienteering_accounts.event.models import Event
from orienteering_accounts.account import perms

from django.utils.translation import ugettext_lazy as _


class EventList(LoginRequiredMixin, FilterView):
    permissions_required = perms.event_view_perms
    template_name = 'event/list.html'
    queryset = Event.objects.order_by('-date')
    filterset_class = EventFilter


class EventDetail(LoginRequiredMixin, View):
    permissions_required = perms.event_view_perms

    def get(self, request, pk):
        event = get_object_or_404(Event, pk=pk)
        form = EventForm(instance=event)
        return render(request, 'event/event_detail.html', {
            'event': event,
            'form': form
        })

    def post(self, request, pk):
        event = get_object_or_404(Event, pk=pk)
        form = EventForm(request.POST, instance=event)
        if not form.is_valid():
            return render(request, 'event/event_detail.html', {
                'event': event,
                'form': form
            })
        event = form.save()
        if form.cleaned_data.get('leader'):
            event.leader.leader_key = uuid.uuid4()
            event.leader.save()
        messages.add_message(
            self.request,
            messages.SUCCESS,
            _('Uloženo')
        )
        return HttpResponseRedirect(reverse('events:list'))


class EventEntries(LoginRequiredMixin, View):
    permissions_required = perms.event_view_perms

    def get(self, request, pk):
        event = get_object_or_404(Event, pk=pk)
        return render(request, 'event/event_entries.html', {
            'event': event,
            'email_recipients': ', '.join(filter(None, event.entries.values_list('account__email', flat=True)))
        })


class EventEntriesPreview(View):
    permissions_required = perms.event_view_perms

    def get(self, request, pk, key):
        get_object_or_404(Account, leader_key=key)
        event = get_object_or_404(Event, pk=pk)

        return render(request, 'event/event_entries_preview.html', {
            'event': event,
            'email_recipients': ', '.join(filter(None, event.entries.values_list('account__email', flat=True)))
        })


class EventBills(View):

    def get(self, request, pk, key):
        get_object_or_404(Account, leader_key=key)
        event = get_object_or_404(Event, pk=pk)

        entries_qs = event.entries.order_by('account__registration_number')

        return render(request, 'event/event_bills.html', {
            'event': event,
            'formset': EventEntryBillFormSet(
                queryset=entries_qs
            )
        })

    def post(self, request, pk, key):
        event = get_object_or_404(Event, pk=pk)

        formset = EventEntryBillFormSet(request.POST, queryset=event.entries.all())

        if formset.is_valid():
            formset.save()
            event.bills_solved = True
            event.processing_state = Event.ProcessingType.BILLS_SOLVED
            event.bills_solved_at = timezone.now()
            event.save(update_fields=['processing_state', 'bills_solved', 'bills_solved_at'])

            return HttpResponseRedirect(reverse('events:bills_success', args=[event.pk, key]))

        return render(request, 'event/event_bills.html', {
            'event': event,
            'formset': formset
        })


class EventBillsSuccess(View):

    def get(self, request, pk, key):
        leader = get_object_or_404(Account, leader_key=key)
        event = get_object_or_404(Event, pk=pk)
        if event.leader.pk != leader.pk:
            raise Http404()

        if not event.bills_solved:
            raise Http404()

        return render(request, 'event/event_bills_success.html')

orienteering_accounts/event/templates/event/event_bills.html
{% extends "base.html" %}{% load i18n forms account entry %}

{% block navbar %}{% endblock %}

{% block main_content %}
    <h1>{{ event.name }} - {% trans "Vyúčtování" %}</h1>

    <form method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        <table class="table table-bordered">
        <thead>
            <tr>
                <th>{% trans "Jméno a Příjmení" %}</th>
                <th>{% trans "Registrační číslo" %}</th>
                <th>{% trans "Kategorie" %}</th>
                <th>{% trans "Startovné" %}</th>
                <th>{% trans "Startovné po příspěvku oddílu" %}</th>
                {% for _, additional_service in event.additional_services.items %}
                    <th>{{ additional_service.NameCZ }}</th>
                {% endfor %}
                <th>{% trans "Dluh" %}</th>
                <th>{% trans "Další náklady" %}</th>
                <th>{% trans "Poznámka" %}</th>
            </tr>
        </thead>
        {% for form in formset %}
            {{ form.id }}
            {% with form.instance as entry %}
                <tr>
                    <td>{{ entry.account.full_name }}</td>
                    <td>{{ entry.account.registration_number }}</td>
                    <td>{{ entry.category_name }}</td>
                    <td>{{ entry.fee }}</td>
                    <td>{{ entry.fee_after_club_discount }}</td>
                    {% for _, additional_service in event.additional_services.items %}
                        <td>{% entry_additional_service_value entry additional_service %}</td>
                    {% endfor %}
                    <td>{% form_field form.debt label=False %}</td>
                    <td>{% form_field form.other_debt label=False %}</td>
                    <td>{% form_field form.debt_note label=False %}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        </table>
        <button type="submit" class="btn btn-success">{% trans "Odeslat" %}</button>
    </form>

{% endblock %}

{% block right-sidebar %}
{% endblock %}

orienteering_accounts/event/templates/event/event_bills_success.html
{% extends "base.html" %}{% load i18n forms account entry %}

{% block navbar %}{% endblock %}

{% block main_content %}
    <h4 style="text-align: center; margin-top: 15px;">Hotovo, díky za kontrolu/úpravu</h4>
{% endblock %}

{% block right-sidebar %}
{% endblock %}

orienteering_accounts/event/templates/event/event_detail.html
{% extends "base.html" %}{% load i18n forms account crispy_forms_tags %}

{% block main_content %}
    <h1>{% trans "Detail závodu" %}</h1>

    <div class="container">
        <div class="row">
            <div class="col-9">
                <h2>{{ event.name }}</h2>
            </div>
            <div class="col-3" style="text-align: right">
                <a class="btn btn-secondary" href="{% url "events:entries" event.pk %}">{% trans "Přihlášky" %}</a>
                {% if event.leader %}
                    <a class="btn btn-secondary" href="{% url "events:bills" event.pk event.leader.leader_key %}">{% trans "Dluhy" %}</a>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {% trans "Datum" %}: {{ event.date }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {% trans "Organizátor" %}: {{ event.organizers }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {% trans "Oblast" %}: {{ event.region }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {% trans "Disciplína" %}: {{ event.discipline.name }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {% trans "Úroveň" %}: {{ event.level.name }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {% trans "Místo" %}: {{ event.venue }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {% trans "ORIS" %}: <a href="{{ event.oris_url }}">{{ event.oris_id }}</a>
            </div>
        </div>
        {% ifnotperm edit_event %}
        <div class="row">
            <div class="col">
                {% trans "Zpracováváno systémem" %}: {{ event.handled|yesno:"Ano,Ne" }}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {% trans "Vedoucí" %}: {{ event.leader|default:"-" }}
            </div>
        </div>
        {% endifnotperm %}
    </div>

    <br>

    {% ifperm edit_event %}
        {% crispy form %}
    {% endifperm %}

{% endblock %}

orienteering_accounts/event/templates/event/event_entries.html
{% extends "base.html" %}{% load i18n forms %}

{% block main_content %}

    <h1>{% trans "Přihlášky" %}</h1>

    {% include "event/includes/event_entries_table.html" %}

    <label for="id_email_recipients">{% trans "Příjemci emailu:" %}</label>
    <input type="text" readonly="readonly" class="form-control js-text-copy" id="id_email_recipients" value="{{ email_recipients }}" data-text-to-copy="{{ email_recipients }}" title="{% trans 'Zkopírováno do schránky' %}">

{% endblock main_content %}

orienteering_accounts/event/templates/event/event_entries_preview.html
{% extends "base.html" %}{% load i18n forms account entry %}

{% block navbar %}{% endblock %}

{% block main_content %}
    <h1>{{ event.name }} - {% trans "Přihlášky" %}</h1>

    {% include "event/includes/event_entries_table.html" with preview=True %}

    <label for="id_email_recipients">{% trans "Příjemci emailu:" %}</label>
    <input type="text" readonly="readonly" class="form-control js-text-copy" id="id_email_recipients" value="{{ email_recipients }}" data-text-to-copy="{{ email_recipients }}" title="{% trans 'Zkopírováno do schránky' %}">

    
{% endblock main_content %}

{% block right-sidebar %}
{% endblock %}

orienteering_accounts/event/templates/event/list.html
{% extends "base.html" %}{% load i18n forms crispy_forms_tags %}

{% block main_content %}

    <h1>{% trans "Seznam závodů" %}</h1>

    {% crispy filter.form %}

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">{% trans "Název" %}</th>
          <th scope="col">{% trans "Datum" %}</th>
          <th scope="col">{% trans "Organizátor" %}</th>
          <th scope="col">{% trans "Oblast" %}</th>
          <th scope="col">{% trans "Typ závodu" %}</th>
          <th scope="col">{% trans "Zpracovat?" %}</th>
          <th scope="col">{% trans "Vedoucí" %}</th>
          <th scope="col">{% trans "ORIS" %}</th>
          <th scope="col">{% trans "Dluhy" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for event in event_list %}
        <tr>
          <td><a href="{% url 'events:detail' event.id %}">{{ event.name }}</a></td>
          <td>{{ event.date }}</td>
          <td>{{ event.organizer_1.abbr }}</td>
          <td>{{ event.region }}</td>
          <td>{{ event.level.name }}</td>
          <td style="text-align: center">{% if event.handled %}<i class="fa fa-check"></i>{% else %}<i class="fa fa-times"></i>{% endif %}</td>
          <td>{{ event.leader }}</td>
          <td><a href="{{ event.oris_url }}">{{ event.oris_id }}</a></td>
            <td style="text-align: center">{% if event.bills_solved %}<i class="fa fa-check"></i>{% else %}<i class="fa fa-times"></i>{% endif %}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock main_content %}