orienteering_accounts/account/urls.py
from django.urls import path, include

from orienteering_accounts.account.views import (
    AccountListView, AccountExportView, AccountDetailView, AccountEditView, TransactionCreate, RoleListView,
    RoleAddView, RoleEditView, AccountTransactionsEmbeddedView, AccountTransactionsView, PaymentPeriodEditView,
    PaymentPeriodListView,
    PaymentPeriodCreateView, TransactionEdit, ClubroomChipNumberView, ClubroomChipNumberExportView,
    BankTransactionListView, AccountPasswordSetView
)

app_name = 'accounts'

role_urlpatterns = ([
    path('', RoleListView.as_view(), name='list'),
    path('add/', RoleAddView.as_view(), name='add'),
    path('<int:pk>/edit/', RoleEditView.as_view(), name='edit'),
], 'role')


payment_period_urlpatterns = ([
    path('', PaymentPeriodListView.as_view(), name='list'),
    path('add/', PaymentPeriodCreateView.as_view(), name='add'),
    path('<int:pk>/edit/', PaymentPeriodEditView.as_view(), name='edit'),
], 'payment_period')


urlpatterns = [
    path('', AccountListView.as_view(), name='list'),
    path('export/', AccountExportView.as_view(), name='export'),
    path('clubroom-chip-list/', ClubroomChipNumberView.as_view(), name='clubroom_chip_list'),
    path('clubroom-chip-list/export/', ClubroomChipNumberExportView.as_view(), name='clubroom_chip_list_export'),
    path('role/', include(role_urlpatterns)),
    path('payment_period/', include(payment_period_urlpatterns)),
    path('<int:pk>/', AccountDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', AccountEditView.as_view(), name='edit'),
    path('<int:pk>/password-change/', AccountPasswordSetView.as_view(), name='password_change'),
    path('<int:pk>/transaction/add/', TransactionCreate.as_view(), name='transaction_add'),
    path('transaction/<int:pk>/edit/', TransactionEdit.as_view(), name='transaction_edit'),
    path('transactions/', AccountTransactionsEmbeddedView.as_view(), name='embedded'),
    path('transactions/<uuid:key>/', AccountTransactionsView.as_view(), name='transactions'),
    path('bank-transactions/', BankTransactionListView.as_view(), name='bank_transactions'),
]

orienteering_accounts/event/urls.py
from django.urls import path

from orienteering_accounts.event.views import EventList, EventDetail, EventBills, EventBillsSuccess, EventEntries, EventEntriesPreview

app_name = 'events'

urlpatterns = [
    path('', EventList.as_view(), name='list'),
    path('<int:pk>/', EventDetail.as_view(), name='detail'),
    path('<int:pk>/entries', EventEntries.as_view(), name='entries'),
    path('<int:pk>/entries/<uuid:key>/', EventEntriesPreview.as_view(), name='entries_preview'),
    path('<int:pk>/bills/<uuid:key>/', EventBills.as_view(), name='bills'),
    path('<int:pk>/bills/<uuid:key>/success/', EventBillsSuccess.as_view(), name='bills_success'),
]

orienteering_accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from orienteering_accounts.account.views import AccountLoginView
from orienteering_accounts.core.views import SettingsEdit


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('', include('orienteering_accounts.account.urls')),  # TODO temporary
    path('settings/', SettingsEdit.as_view(), name='settings_detail'),
    path('accounts/', include('orienteering_accounts.account.urls')),
    path('events/', include('orienteering_accounts.event.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orienteering_accounts/account/forms.py
from decimal import Decimal

from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, SetPasswordForm
from django.core.validators import MinValueValidator
from django.db import models
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _

from orienteering_accounts.account.models import Transaction, Role, Permission, Account, PaymentPeriod


class LoginForm(AuthenticationForm):
    def __init__(self, request=None, *args, **kwargs):
        super(LoginForm, self).__init__(request=request, *args, **kwargs)


class PaymentPeriodForm(forms.ModelForm):

    class Meta:
        model = PaymentPeriod
        fields = ['date_from', 'date_to']
        widgets = {
            'date_from': forms.DateInput(attrs={'class':'form-control', 'type':'date'}),
            'date_to': forms.DateInput(attrs={'class':'form-control', 'type':'date'})
        }


class TransactionEditForm(forms.ModelForm):

    class TransactionType(models.TextChoices):
        INCOME = 'INCOME', _('Příjem')
        COST = 'COST', _('Výdaj')

    transaction_type = forms.ChoiceField(choices=TransactionType.choices, initial=TransactionType.INCOME, label=_('Typ transakce'))

    class Meta:
        model = Transaction
        fields = ['amount', 'note', 'purpose', 'period']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk and self.instance.amount < 0:
            self.initial['amount'] = self.instance.amount * -1
        self.fields['amount'].validators = [MinValueValidator(Decimal(0))]

    def clean(self):
        cleaned_data = super().clean()

        if cleaned_data['purpose'] == Transaction.TransactionPurpose.CLUB_MEMBERSHIP and not cleaned_data['period']:
            self.add_error('period', _('Je nutné zvolit období pro platbu v případě oddílového příspěvku'))

        if cleaned_data['purpose'] == Transaction.TransactionPurpose.OTHER and not cleaned_data['note']:
            self.add_error('note', _('Poznámku je nutné uvést v případě ostatních plateb'))

        if self.cleaned_data['transaction_type'] == TransactionEditForm.TransactionType.COST:
            self.cleaned_data['amount'] *= -1

        return cleaned_data


class TransactionAddForm(TransactionEditForm):

    class Meta:
        model = Transaction
        fields = ['amount', 'note', 'account', 'purpose', 'period']


class AccountEditForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.email_before = self.instance.email
        self.email2_before = self.instance.email2

    class Meta:
        model = Account
        fields = ['role', 'email', 'email2', 'is_active', 'clubroom_chip_number']


class RoleForm(ModelForm):
    permissions = forms.ModelMultipleChoiceField(
        queryset=Permission.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        label=_('Práva'),
        required=False
    )

    class Meta:
        model = Role
        fields = ['name', 'permissions']

orienteering_accounts/core/utils/forms.py
def add_class(widget, css_class):
    """ Helper function - adds CSS class to widget

    """
    attrs = widget.attrs or {}
    if 'class' in attrs:
        attrs['class'] = '%s %s' % (attrs['class'], css_class)
    else:
        attrs['class'] = css_class
    widget.attrs = attrs

orienteering_accounts/account/views.py
import io
import xlsxwriter
import jwt

from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.core.files.base import ContentFile
from django.db import transaction
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, DetailView, UpdateView, ListView, TemplateView
from django.utils.translation import ugettext_lazy as _, gettext
from django_filters.views import FilterView

from requests import HTTPError

from orienteering_accounts.account.filters import AccountFilter
from orienteering_accounts.account.forms import TransactionAddForm, AccountEditForm, PaymentPeriodForm, \
    TransactionEditForm
from orienteering_accounts.account.models import Transaction, Account, PaymentPeriod, BankTransaction
from orienteering_accounts.account import perms
from orienteering_accounts.account.forms import RoleForm
from orienteering_accounts.account.models import Role


from django.contrib.auth.views import LoginView, PasswordChangeView

from orienteering_accounts.account.forms import LoginForm
from orienteering_accounts.core.mixins import PermissionsRequiredMixin
from orienteering_accounts.core.models import ChangeLog


class PaymentPeriodListView(LoginRequiredMixin, PermissionsRequiredMixin, ListView):
    template_name = 'account/payment_period/list.html'
    model = PaymentPeriod
    permissions_required = perms.payment_period_view_perms


class PaymentPeriodCreateView(LoginRequiredMixin, PermissionsRequiredMixin, CreateView):
    model = PaymentPeriod
    form_class = PaymentPeriodForm
    template_name = 'account/payment_period/create.html'
    permissions_required = perms.payment_period_create_perms

    def get_success_url(self):
        return reverse('accounts:payment_period:list')


class PaymentPeriodEditView(LoginRequiredMixin, PermissionsRequiredMixin, UpdateView):
    model = PaymentPeriod
    form_class = PaymentPeriodForm
    template_name = 'account/payment_period/edit.html'
    permissions_required = perms.payment_period_edit_perms

    def get_success_url(self):
        return reverse('accounts:payment_period:list')


class AccountLoginView(LoginView):
    form_class = LoginForm
    redirect_authenticated_user = True


class AccountListView(LoginRequiredMixin, PermissionsRequiredMixin, FilterView):
    template_name = 'account/list.html'
    filterset_class = AccountFilter
    permissions_required = perms.account_view_perms

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(object_list=object_list, **kwargs)
        if 'o' in self.request.GET:
            ordering = self.request.GET['o']
            if ordering.startswith('-'):
                context_data.update(descendant=False)
            else:
                context_data.update(descendant=True)
            context_data.update(ordering=ordering)
        return context_data


class AccountExportView(LoginRequiredMixin, PermissionsRequiredMixin, View):
    permissions_required = perms.account_view_perms

    def get(self, *args, **kwargs):
        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output)
        worksheet = workbook.add_worksheet()

        worksheet.set_column(0, 0, width=20)
        worksheet.set_column(0, 1, width=20)
        worksheet.set_column(0, 2, width=20)
        worksheet.set_column(0, 3, width=20)

        worksheet.write(0, 0, gettext('Jméno a Příjmení'))
        worksheet.write(0, 1, gettext('Registrační číslo'))
        worksheet.write(0, 2, gettext('Příspěvky uhrazeny'))
        worksheet.write(0, 3, gettext('Dluhy uhrazeny'))

        for i, account in enumerate(Account.objects.order_by('last_name')):

            row = i+1

            worksheet.write(row, 0, account.full_name_inv)
            worksheet.write(row, 1, account.registration_number)
            worksheet.write(row, 2, gettext('ANO') if account.club_membership_paid else gettext('NE'))
            worksheet.write(row, 3, gettext('ANO') if account.debts_paid else gettext('NE'))

        worksheet.fit_to_pages(1, 0)
        workbook.close()
        output.seek(0)

        response = HttpResponse(
            ContentFile(output.read()),
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        response['Content-Disposition'] = 'attachment; filename=accounts.xlsx'

        return response


class AccountDetailView(LoginRequiredMixin, PermissionsRequiredMixin, DetailView):
    queryset = Account.all_objects.all()
    template_name = 'account/detail.html'
    permissions_required = perms.account_view_perms


class AccountEditView(LoginRequiredMixin, PermissionsRequiredMixin, UpdateView):
    queryset = Account.all_objects.all()
    template_name = 'account/edit.html'
    permissions_required = perms.account_edit_perms
    form_class = AccountEditForm

    def get_success_url(self):
        return reverse('accounts:detail', args=[self.object.pk])

    def form_valid(self, form: AccountEditForm):
        response = super().form_valid(form)
        if 'is_active'in form.changed_data and not self.object.is_active:
            self.object.remove_from_google_workspace_group()
        if form.email_before != self.object.email:
            self.object.remove_from_google_workspace_group(email=form.email_before)
            self.object.add_to_google_workspace_group()
        if form.email2_before != self.object.email2:
            if not self.object.email2:
                self.object.remove_from_google_workspace_group(email2=form.email2_before)
            elif not form.email2_before:
                self.object.add_to_google_workspace_group()
            else:
                self.object.remove_from_google_workspace_group(email2=form.email2_before)
                self.object.add_to_google_workspace_group()
        return response


class AccountPasswordSetView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'account/password_change.html'
    permissions_required = perms.account_edit_perms
    form_class = SetPasswordForm

    def get_success_url(self):
        return reverse('accounts:detail', args=[self.kwargs['pk']])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(user=Account.objects.get(pk=self.kwargs['pk']))
        return kwargs

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data.update(user=Account.objects.get(pk=self.kwargs['pk']))
        return context_data


class TransactionCreate(LoginRequiredMixin, PermissionsRequiredMixin, CreateView):
    template_name = 'transaction/create.html'
    model = Transaction
    form_class = TransactionAddForm
    permissions_required = perms.transaction_create_perms

    def get_form(self, *args, **kwargs):
        form = super(TransactionCreate, self).get_form(*args, **kwargs)
        form.fields['account'].widget = forms.HiddenInput()
        form.fields['account'].required = False
        return form

    def get_initial(self):
        initial = super().get_initial()
        initial.update(
            account=self.kwargs['pk']
        )
        return initial

    def get_account(self):
        return get_object_or_404(Account, id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data.update(account=self.get_account())
        return context_data

    def form_valid(self, form):
        try:
            with transaction.atomic():
                created_transaction = form.save()
                ChangeLog.objects.create(
                    owner_id=self.request.user.pk,
                    instance_type=ContentType.objects.get_for_model(Transaction),
                    instance_id=created_transaction.pk,
                    change_type=ChangeLog.ChangeType.CREATE
                )
                account = created_transaction.account
                if created_transaction.purpose in [
                    Transaction.TransactionPurpose.CLUB_MEMBERSHIP,
                    Transaction.TransactionPurpose.DEBTS
                ] and account.is_late_with_club_membership_payment:
                    account.add_entry_rights_in_oris()
                    account.is_late_with_club_membership_payment = False
                    account.save()
        except HTTPError:
            messages.add_message(
                self.request,
                messages.ERROR,
                _('Transakci nelze přidat, chyba při komunikaci s ORIS.')
            )

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('accounts:detail', args=[self.kwargs['pk']])


class TransactionEdit(LoginRequiredMixin, PermissionsRequiredMixin, UpdateView):
    template_name = 'transaction/edit.html'
    model = Transaction
    form_class = TransactionEditForm
    permissions_required = perms.transaction_edit_perms

    def get_success_url(self):
        return reverse('accounts:detail', args=[self.get_form().instance.account.pk])


class AccountTransactionsEmbeddedView(TemplateView):
    template_name = 'account/embedded.html'

    def get(self, request, *args, **kwargs):
        token = request.GET.get('auth')

        if not token:
            return HttpResponse('Auth token is missing', status=400)

        try:
            payload = jwt.decode(token, settings.API_SECRET, algorithms='HS256')
        except jwt.InvalidTokenError:
            return HttpResponse('Token is invalid', status=401)

        if 'registration_number' not in payload:

orienteering_accounts/core/views.py
from datetime import datetime

from django.views.generic import UpdateView

from orienteering_accounts.core.models import Settings


class SettingsEdit(UpdateView):
    model = Settings
    fields = ['club_membership_deadline']
    template_name = 'core/settings_update.html'

    def get_object(self, *args, **kwargs):
        return self.model.objects.get_or_create(
            id=1,
            defaults={'club_membership_deadline': datetime(datetime.today().year, 2, 28, 23, 59, 59)}
        )[0]

orienteering_accounts/templates/base.html
{% load static i18n account %}
<!doctype html>
<html lang="cs-cs">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block title %} | {% trans 'SKOB Zlín - správa účtů' %}{% endblock title %}</title>

        {% block metas %}
        <meta name="description" content="Dashboard UI Kit">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% endblock metas %}

        {% block favicons %}
        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
        {% endblock favicons %}

        {% block stylesheets %}
        <!-- Stylesheet -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fontawesome-free-5.15.2-web/css/all.css' %}">
        {% endblock stylesheets %}

        {% block scripts %}
            <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
            <script src="{% static 'js/popper.min.js' %}"></script>
            <script src="{% static 'js/bootstrap.min.js' %}"></script>
            <script src="{% static 'js/core.js' %}"></script>
        {% endblock scripts %}
    </head>
    <body>
        {% block navbar %}
        {% if not request.user.is_anonymous %}
            {% include "navbar.html" %}
        {% endif %}
        {% endblock %}
        <div class="container" style="max-width: 1280px; padding-bottom: 15px;">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <div class="row" >
                <div class="col-10">
                {% block main_content %}
                {% endblock main_content %}
                </div>
                {% block right-sidebar %}
                {% if not request.user.is_anonymous %}
                    {% ifperm view_change_log %}
                        <div class="col-2" style="border-left: 2px solid black;">
                            <h3>{% trans "Historie změn:" %}</h3>
                            <div class="container">
                            {% for change_log in request.user.change_logs.all %}
                                <div class="row">{{ change_log|safe }}</div>
                                <hr style="margin-top: 5px; margin-bottom: 5px; border-width: 2px;">
                            {% empty %}
                                <div class="row">{% trans "Žádné změny" %}</div>
                            {% endfor %}
                            </div>
                        </div>
                    {% endifperm %}
                {% endif %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

orienteering_accounts/templates/edit.html
{% extends 'base.html' %}{% load i18n forms %}

{% block main_content %}
    <h1>{% block title %}{% endblock %}</h1>

    <div class="container">
        <div class="row">
            <form method="post">{% csrf_token %}
                {% block form_fields %}
                    {% if form.fields_data %}
                        {% for field in form.fields_data %}
                            {% form_field field %}
                        {% endfor %}
                    {% else %}
                        {% for field in form %}
                            {% form_field field %}
                        {% endfor %}
                    {% endif %}
                {% endblock form_fields %}

                {% block buttons %}
                    <a href="{{ object.get_absolute_url }}" class="btn btn-secondary">
                        {% trans 'Zpět' %}
                    </a>
                    <button type="submit" class="btn btn-success">
                        {% trans 'Uložit' %}
                    </button>
                {% endblock buttons %}
            </form>
        </div>
    </div>
    
{% endblock %}

orienteering_accounts/templates/navbar.html
{% load account i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <a class="navbar-brand" href="/">{% trans "IS SKOB Zlín" %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        {% ifperm view_events %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "events:list" %}">{% trans "Události" %}</a>
            </li>
        {% endifperm %}
        {% ifperm view_account %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {% trans "Účty" %}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% ifperm view_account %}
                    <a class="dropdown-item" href="{% url "accounts:list" %}">{% trans "Účty" %}</a>
                    <a class="dropdown-item" href="{% url "accounts:clubroom_chip_list" %}">{% trans "Čipy" %}</a>
                  {% endifperm %}
                  {% ifperm view_role %}
                    <a class="dropdown-item" href="{% url "accounts:role:list" %}">{% trans "Role" %}</a>
                  {% endifperm %}
                  {% ifperm view_payment_period %}
                    <a class="dropdown-item" href="{% url "accounts:payment_period:list" %}">{% trans "Platební období" %}</a>
                  {% endifperm %}
                  {% ifperm view_bank_transaction_list %}
                      <a class="dropdown-item" href="{% url "accounts:bank_transactions" %}">{% trans "Bankovní transakce" %}</a>
                  {% endifperm %}
              </div>
            </li>
        {% endifperm %}
            <li class="nav-item dropdown">
              <a class="nav-link" href="{% url "events:list" %}">{% trans "Události" %}</a>
            </li>
        {% ifperm view_event %}
        {% endifperm %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:detail" request.user.id %}">{% trans "Můj účet" %}</a>
        </li>
    </ul>
  </div>
  </div>
</nav>